auto_save: False
background_color: ''
chain_cursors: False
clinical_mode: True
max_projects: 5
name: MIA
nb_slices_max: '10'
opened_projects: []
show_all_slices: False
text_color: ''
thumbnail_tag: SequenceName
use_matlab: False
use_spm: False
use_spm_standalone: False
